#!/bin/bash

MPLBACKEND=Agg python -c "import matplotlib.pyplot"  # Build font cache.

pip install bluesky-tutorial-utils/

# This is needed until we bump to JupyterLab 3.
jupyter labextension install @jupyter-widgets/jupyterlab-manager jupyter-matplotlib
